on:
  push:
    branches:
    - main

jobs:
  deploy:
    name: Deploy to eklipsed.net
    runs-on: ubuntu-latest
    steps:
    - run: |
        curl -X POST https://blog.eklipsed.net/admin/github-deploy
